# MediaWiki with MariaDB
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
services:
  mediawiki:
    #image: mediawiki
    build: .
    depends_on:
      - database
    restart: always
    ports:
      - 8080:80
    links:
      - database
    volumes:
      - images:/var/www/html/images
      - ./extensions:/var/www/html/extensions
      - ./skins:/var/www/html/skins
      - ./logo.png:/var/www/html/resources/assets/logo.png
      - ./config:/conf
    environment:
      DEBUG: true
      MW_SITE_NAME: "mediawiki"
      MW_META_NAMESPACE: "mediawiki"
      MW_SITE_SERVER: "http://localhost"
      MW_ENABLE_EMAIL: true
      MW_ENABLE_USER_EMAIL: true
      MW_EMERGENCY_CONTACT: "apache@localhost"
      MW_PASSWORD_SENDER: "apache@localhost"
      MW_DB_NAME: "mediawiki"
      MW_DB_USER: "mediawiki"
      MW_DB_PASSWORD: "change_me_1234"
      MW_ENABLE_UPLOADS: true
      MW_ENABLE_INSTANT_COMMONS: true
      MW_SECRET_KEY: "Secure64CharRandomHere"
      MW_UPGRADE_KEY: "SecurePasswordForWebUpdates"
      MW_DEFAULT_SKIN: "timeless"
      MW_ENABLED_SKINS: "Timeless"
      MW_ENABLED_EXTENSIONS: ""
      
  # This key also defines the name of the database host used during setup instead of the default "localhost"
  database:
    image: mariadb
    restart: always
    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_DATABASE: mediawiki
      MYSQL_USER: mediawiki
      MYSQL_PASSWORD: 'change_me_1234'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
  images: